version: '3.8'

services:
  robust-image-matcher:
    build: .
    ports:
      - "7000:7000"
    environment:
      - FLASK_ENV=production
      - PORT=7000
    volumes:
      - ./uploads:/app/uploads  # Persist uploads directory
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:7000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    deploy:
      resources:
        limits:
          memory: 2G
        reservations:
          memory: 1G

  # Optional: Add nginx reverse proxy
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - robust-image-matcher
    restart: unless-stopped
    profiles:
      - with-proxy

networks:
  default:
    driver: bridge
