post https://lostmatcher-model-server.onrender.com/compare_items
Content-Type: application/json

{
        "description1": "red umbrella.",
        "description2": "umbrella that is red"
}

### test locally
post http://localhost:8000/compare_items
Content-Type: application/json
